version: '3.7'
services:
  measure-shelter:
    image: measure-shelter
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo:database
    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password